### PR TITLE
Volunteers page

### LINKED ISSUE #6: Volunteers Management System
- Search/Filter of volunteer programmers 
- Ability to sign up as a volunteer and update profile 
- Links to preferred User portfolio pages (Default will be LinkedIn)
- Feel free to add

### PR DESCRIPTION
**Pull request by Luukeeeee**
## Rationale

What does this pull request do?

## Advice for Reviewers & Testing Notes

- Explain how your change should be reviewed, and where reviewers should direct their attention.
- Explain (where relevant) how your change can be tested.

## Screenshots:

- Add a screenshot or two of your changes, where applicable.

## Issue Resolved

*Note - This allows the issue to be automatically linked to the PR once the PR is submitted for review*
- Fixes #6

### CODE REVIEW

**Comment by QjStout** [comment]
Thanks @Luukeeeee I'll go through it tomorrow or Sunday at the latest

**Comment by Luukeeeee** [comment]
Thanks @QjStout , it's not in hurry anyway. Enjoying your weekend.

**Comment by engramar** [comment]
Thanks @Luukeeeee! For future PR requests, try to populate this template whenever possible but good start.
image

**Comment by engramar** [comment]
Regarding the navbar, can we interchange the below 
image

**Comment by Luukeeeee** [comment]
Morning @engramar , got you. I'll get used to the procedure. To be honest, it's my first time of making a pull request😅
I've learnt a lot of things from you guys. Thanks again.

**Comment by Luukeeeee** [comment]
> Regarding the navbar, can we interchange the below 
> image
> 

Sure, I'll fix it up.

**Comment by engramar** [comment]
I really like your work here, @Luukeeeee . Just minor comments. Please make sure to make this font bigger and similar to the font family (in general) as the one on the home page. Also, I wonder why the LinkedIn icon is showing as colour orange instead of white. Please add your profile as well as 'Web Developer'. =)  You can give me your head shot and I can give you back the same image with blue background same as the mentors. Thanks again.
image

**Comment by engramar** [comment]
> Morning @engramar , got you. I'll get used to the procedure. To be honest, it's my first time of making a pull request😅 I've learnt a lot of things from you guys. Thanks again.

No worries mate. I think the process is working as expected. You will just need the approval from @QjStout and @rpgarde to merge but it is good to know that Vercel automatically creates staging area (i.e. PREVIEW) in which we can see your changes quickly online without running it locally. 
image

**Comment by engramar** [comment]
BTW @Luukeeeee , Just around the process. I also assigned #6 to you and moved the related card to 'In progress' swimlane. You can see our project board here -> https://github.com/codesydney/codesydneywebsite/projects/1
image

**Comment by Luukeeeee** [comment]
> I really like your work here, @Luukeeeee . Just minor comments. Please make sure to make this font bigger and similar to the font family (in general) as the one on the home page. Also, I wonder why the LinkedIn icon is showing as colour orange instead of white. Please add your profile as well as 'Web Developer'. =) You can give me your head shot and I can give you back the same image with blue background same as the mentors. Thanks again. image

I will check them out. The color of Linkdin Icons are white on my side, anyway I'll add a font-color to it to see whether will fixe it. Also, for those volunteers' data, if you think it's would be a good way to keep it in the js file rather than airtable at this beginning point of time. I would save those avatar photos to the public folder(I am using the url of the old website currently.). I will send your my photo, however, before that I will think about my description first. : P

**Comment by engramar** [comment]
> > I really like your work here, @Luukeeeee . Just minor comments. Please make sure to make this font bigger and similar to the font family (in general) as the one on the home page. Also, I wonder why the LinkedIn icon is showing as colour orange instead of white. Please add your profile as well as 'Web Developer'. =) You can give me your head shot and I can give you back the same image with blue background same as the mentors. Thanks again. image
> 
> I will check them out. The color of Linkdin Icons are white on my side, anyway I'll add a font-color to it to see whether will fixe it. Also, for those volunteers' data, if you think it's would be a good way to keep it in the js file rather than airtable at this beginning point of time. I would save those avatar photos to the public folder(I am using the url of the old website currently.). I will send your my photo, however, before that I will think about my description first. : P

Yes @Luukeeeee, Just keep them in the JS file at this stage. We will look at Airtable if it becomes too much. LinkedIn is a good place to get your brief description. =) BTW, I also added you as contributor to this project. You can see it on my profile. Will wait for your headshot. Cheers.
image

**Comment by Luukeeeee** [comment]
@engramar done, cheers.

**Comment by engramar** [comment]
Thanks @Luukeeeee . Saw all your changes. Perfect! Let us wait for @QjStout and @rpgarde to approve the PR and all looks good! Thanks again. I will wait for your photo, btw. =)

**Review by QjStout — APPROVED** [review]
I'm happy to approve it.

In the future, keep the scope of your merge request to one story. It's great that you made changes to the 404 page and what not, but those things should be their own story.
Good rule of thumb, a PR should optimally only change like 1-3 files and if you're getting past 8+ files changed you should consider breaking the story down into smaller stories.

**Comment by QjStout** [comment]
Congrats on your first PR @Luukeeeee. Smash that merge button whenever you're ready

**Comment by Luukeeeee** [comment]
> Congrats on your first PR @Luukeeeee. Smash that merge button whenever you're ready

thanks@QjStout

**Comment by Luukeeeee** [comment]
> I'm happy to approve it.
> 
> In the future, keep the scope of your merge request to one story. It's great that you made changes to the 404 page and what not, but those things should be their own story.
> Good rule of thumb, a PR should optimally only change like 1-3 files and if you're getting past 8+ files changed you should consider breaking the story down into smaller stories.

Sure, thank you for your information. I learnt a lot from you guys. Thanks again.

**Pull request merged**
