### PR TITLE
Refactor: convert ServiceTwo into a function component

### LINKED ISSUE #92: Convert ServiceTwo to Function Component
- Convert ServiceTwo from a class component to a function component

- File [link](https://github.com/codesydney/codesydneywebsite/blob/main/src/elements/service/ServiceTwo.jsx) and path  src/elements/service/ServiceTwo.jsx

### PR DESCRIPTION
**Pull request by foadbotan**
Refactor of ServiceTwo from a class component to a function component. 

- Fixes [#92](https://github.com/codesydney/codesydneywebsite/issues/92)
- Remove unused lines of code

### CODE REVIEW

**Comment by foadbotan** [comment]
This component has some unnecessary code, but I'm unsure if I should refactor it in this pull request or a separate one.

**Comment by davidtaing** [comment]
> This component has some unnecessary code, but I'm unsure if I should refactor it in this pull request or a separate one.

This PR is a refactor, so please go ahead with the additional refactoring.

But the code looks good so far. Thanks for the good work!

**Review by davidtaing — APPROVED** [review]
Thanks for the good work @foadbotan.

I noticed that this component isn't being used by the website. Since we started with a template, there will be multiple versions of the same component. Moving forward, let's skip the components that aren't being used.

But otherwise, changes look good. Approved!

**Comment by foadbotan** [comment]
I thought so also, given how strangely the code is structured. But ServiceTwo is the award section on the home page. 

I wasn't sure if I should move and rename it.

Xnapper-2022-12-01-18 43 08

**Comment by davidtaing** [comment]
Well, you are completely right. That's my bad, sorry about that!

Maybe I should catch up on some sleep hahaha.

**Comment by foadbotan** [comment]
All good mate. 

It's taking me longer to figure out which components are being used than it is to refactor.

**Pull request merged**
