### PR TITLE
Clickable photos

### LINKED ISSUE #51: Make project photos clickable links
Visitors should be able to click on the project photo and be taken directly to the project website.

Not sure how to assign to self.

### PR DESCRIPTION
**Pull request by serhiicss**
## Rationale

Photos of the projects are now clickable links to the project destination.

## Advice for Reviewers & Testing Notes

Added a href tags and links to the photos.

## Issue Resolved

*Note - This allows the issue to be automatically linked to the PR once the PR is submitted for review*
- Fixes #51

### CODE REVIEW

**Comment by QjStout** [comment]
Hey @serhiicss, didn't notice these PRs. I'll get to them soon. Sorry about the wait.

**Comment by QjStout** [comment]
Hey @serhiicss, looks good mate.

I need you to fix up these merge conflicts before I can approve though. No fault of yours, there were just a couple other PRs that went in that created conflicts.

**Comment by QjStout** [comment]
@serhiicss and again, feel free to DM me if it's been a day or two and I haven't done your PR. We use GitLab at my work so it's easy for me to miss the GitHub notifications as I'm not on it regularly.

**Comment by serhiicss** [comment]
> Hey @serhiicss, looks good mate.
> 
> I need you to fix up these merge conflicts before I can approve though. No fault of yours, there were just a couple other PRs that went in that created conflicts.

I will asap. Just started a new job so a little short on time. Thanks!

**Comment by QjStout** [comment]
No problem at all.
Congratulations on the new gig 🎉

**Pull request closed without merging**
